-- LittleHelper AI Database Migration Script
-- Run this script if you have an existing database that's missing columns
-- Execute in MySQL Workbench or command line: mysql -u root -p littlehelper_ai < migrations.sql

USE littlehelper_ai;

-- Add missing columns to users table
ALTER TABLE users ADD COLUMN IF NOT EXISTS tos_accepted BOOLEAN DEFAULT FALSE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS tos_accepted_at DATETIME NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS tos_version VARCHAR(20) NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS display_name VARCHAR(255) NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS avatar_url TEXT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS registration_ip VARCHAR(45) NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS last_login_ip VARCHAR(45) NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS credits_enabled BOOLEAN DEFAULT TRUE;

-- Add missing columns to chat_history table
ALTER TABLE chat_history ADD COLUMN IF NOT EXISTS is_valid BOOLEAN DEFAULT TRUE;
ALTER TABLE chat_history ADD COLUMN IF NOT EXISTS invalidated_at DATETIME NULL;

-- Create tos_versions table if not exists
CREATE TABLE IF NOT EXISTS tos_versions (
    id VARCHAR(36) PRIMARY KEY,
    version VARCHAR(20) NOT NULL UNIQUE,
    title VARCHAR(255) NOT NULL,
    content JSON NOT NULL,
    effective_date DATETIME NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- Insert default TOS version if not exists
INSERT IGNORE INTO tos_versions (id, version, title, content, effective_date, created_at) VALUES
('tos-v1', '1.0', 'Terms of Service', 
 '{"title":"Terms of Service","sections":[{"title":"1. Acceptance of Terms","content":"By accessing or using LittleHelper AI, you agree to be bound by these Terms of Service."},{"title":"2. Description of Service","content":"LittleHelper AI provides AI-powered code generation and development assistance."},{"title":"3. No Warranty","content":"THE SERVICE IS PROVIDED AS IS WITHOUT WARRANTIES OF ANY KIND."},{"title":"4. Limitation of Liability","content":"IN NO EVENT SHALL LITTLEHELPER AI BE LIABLE FOR ANY DAMAGES ARISING FROM YOUR USE OF THE SERVICE."},{"title":"5. User Responsibility","content":"You are solely responsible for reviewing and testing all code generated by the Service."}],"disclaimer":"BY USING THIS SERVICE, YOU ACKNOWLEDGE THAT AI-GENERATED CODE MAY CONTAIN ERRORS."}',
 NOW(), NOW());

-- Update all subscription plans
INSERT INTO subscription_plans (id, name, description, price_monthly, price_yearly, daily_credits, max_concurrent_workspaces, allows_own_api_keys, features, sort_order, is_active) VALUES
('free', 'Free', 'Basic access with limited credits', 0, 0, 50, 1, FALSE, '["50 daily credits", "1 workspace", "Basic code generation", "Community support"]', 0, TRUE),
('starter', 'Starter', 'For individual developers getting started', 9.99, 99.00, 200, 3, FALSE, '["200 daily credits", "3 workspaces", "All 7 AI agents", "Priority queue", "Email support"]', 1, TRUE),
('pro', 'Pro', 'For professional developers and freelancers', 29.99, 299.00, 1000, 10, TRUE, '["1000 daily credits", "10 workspaces", "All 7 AI agents", "Own API keys", "Advanced AI models", "Priority support"]', 2, TRUE),
('team', 'Team', 'For small teams and startups', 79.99, 799.00, 3000, 25, TRUE, '["3000 daily credits", "25 workspaces", "All 7 AI agents", "Own API keys", "Team collaboration", "Priority support", "Custom integrations"]', 3, TRUE),
('enterprise', 'Enterprise', 'For large teams and organizations', 199.99, 1999.00, 10000, -1, TRUE, '["10000 daily credits", "Unlimited workspaces", "All 7 AI agents", "Own API keys", "Custom AI models", "SLA support", "Custom integrations", "Dedicated account manager"]', 4, TRUE)
ON DUPLICATE KEY UPDATE 
    name = VALUES(name),
    description = VALUES(description),
    price_monthly = VALUES(price_monthly),
    price_yearly = VALUES(price_yearly),
    daily_credits = VALUES(daily_credits),
    max_concurrent_workspaces = VALUES(max_concurrent_workspaces),
    allows_own_api_keys = VALUES(allows_own_api_keys),
    features = VALUES(features),
    sort_order = VALUES(sort_order);

-- Update all credit packages
INSERT INTO credit_packages (id, name, credits, price, sort_order, is_active) VALUES
('pack-50', 'Starter Pack', 50, 2.99, 0, TRUE),
('pack-100', '100 Credits', 100, 4.99, 1, TRUE),
('pack-250', '250 Credits', 250, 9.99, 2, TRUE),
('pack-500', '500 Credits', 500, 17.99, 3, TRUE),
('pack-1000', '1000 Credits', 1000, 29.99, 4, TRUE),
('pack-2500', '2500 Credits', 2500, 69.99, 5, TRUE),
('pack-5000', '5000 Credits', 5000, 129.99, 6, TRUE),
('pack-10000', '10000 Credits', 10000, 229.99, 7, TRUE)
ON DUPLICATE KEY UPDATE 
    name = VALUES(name),
    credits = VALUES(credits),
    price = VALUES(price),
    sort_order = VALUES(sort_order);

-- Update free AI providers
INSERT INTO free_ai_providers (id, name, provider, api_key, model, is_enabled, priority, created_at, updated_at) VALUES
('groq', 'Groq (Free)', 'groq', '', 'llama-3.1-70b-versatile', TRUE, 1, NOW(), NOW()),
('together', 'Together AI (Free)', 'together', '', 'meta-llama/Llama-3.2-11B-Vision-Instruct-Turbo', FALSE, 2, NOW(), NOW()),
('huggingface', 'HuggingFace (Free)', 'huggingface', '', 'microsoft/DialoGPT-large', FALSE, 3, NOW(), NOW()),
('openrouter', 'OpenRouter (Free)', 'openrouter', '', 'google/gemma-2-9b-it:free', FALSE, 4, NOW(), NOW()),
('ollama', 'Local Ollama (Free)', 'ollama', '', 'qwen2.5-coder:1.5b', FALSE, 5, NOW(), NOW())
ON DUPLICATE KEY UPDATE 
    name = VALUES(name),
    model = VALUES(model),
    updated_at = NOW();

SELECT 'Migration completed successfully!' AS Status;
