import { useState, useEffect } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { motion, AnimatePresence } from 'framer-motion';
import { useAuth } from '../../lib/auth';
import { Button } from '../../components/ui/button';
import { Input } from '../../components/ui/input';
import { Label } from '../../components/ui/label';
import { Checkbox } from '../../components/ui/checkbox';
import { ScrollArea } from '../../components/ui/scroll-area';
import { 
    Eye, EyeOff, Zap, ArrowLeft, Check, X, 
    AlertTriangle, FileText, Shield 
} from 'lucide-react';
import api from '../../lib/api';

// Terms of Service Modal Component
function TOSModal({ isOpen, onAccept, onDecline }) {
    const [terms, setTerms] = useState(null);
    const [loading, setLoading] = useState(true);
    const [scrolledToEnd, setScrolledToEnd] = useState(false);

    useEffect(() => {
        if (isOpen) {
            loadTerms();
        }
    }, [isOpen]);

    const loadTerms = async () => {
        try {
            const res = await api.get('/legal/terms');
            setTerms(res.data);
        } catch (error) {
            // Use default terms if API fails
            setTerms({
                version: "1.0",
                content: {
                    title: "Terms of Service",
                    sections: [
                        {
                            title: "1. Acceptance of Terms",
                            content: "By accessing or using LittleHelper AI, you agree to be bound by these Terms of Service."
                        },
                        {
                            title: "2. No Warranty",
                            content: "THE SERVICE IS PROVIDED 'AS IS' AND 'AS AVAILABLE' WITHOUT WARRANTIES OF ANY KIND."
                        },
                        {
                            title: "3. Limitation of Liability",
                            content: "WE SHALL NOT BE LIABLE FOR ANY DAMAGES RESULTING FROM YOUR USE OF THE SERVICE OR ANY CODE GENERATED."
                        },
                        {
                            title: "4. User Responsibility",
                            content: "You are solely responsible for reviewing, testing, and validating all code generated by the Service."
                        }
                    ],
                    disclaimer: "BY USING THIS SERVICE, YOU ACKNOWLEDGE THAT AI-GENERATED CODE MAY CONTAIN ERRORS AND YOU ASSUME ALL RISKS."
                }
            });
        } finally {
            setLoading(false);
        }
    };

    const handleScroll = (e) => {
        const { scrollTop, scrollHeight, clientHeight } = e.target;
        if (scrollTop + clientHeight >= scrollHeight - 20) {
            setScrolledToEnd(true);
        }
    };

    if (!isOpen) return null;

    return (
        <AnimatePresence>
            <motion.div
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                exit={{ opacity: 0 }}
                className="fixed inset-0 z-50 flex items-center justify-center bg-black/80 backdrop-blur-sm p-4"
            >
                <motion.div
                    initial={{ opacity: 0, scale: 0.95, y: 20 }}
                    animate={{ opacity: 1, scale: 1, y: 0 }}
                    exit={{ opacity: 0, scale: 0.95, y: 20 }}
                    className="w-full max-w-2xl bg-[#0B0F19] border border-white/10 rounded-2xl shadow-2xl overflow-hidden"
                >
                    {/* Header */}
                    <div className="p-6 border-b border-white/10 bg-gradient-to-r from-fuchsia-500/10 to-cyan-500/10">
                        <div className="flex items-center gap-3">
                            <div className="w-12 h-12 rounded-xl bg-gradient-to-br from-fuchsia-500 to-cyan-500 flex items-center justify-center">
                                <FileText className="w-6 h-6 text-white" />
                            </div>
                            <div>
                                <h2 className="text-xl font-bold">Terms of Service</h2>
                                <p className="text-sm text-gray-400">Please read and accept to continue</p>
                            </div>
                        </div>
                    </div>

                    {/* Content */}
                    {loading ? (
                        <div className="p-8 flex items-center justify-center">
                            <div className="w-8 h-8 border-2 border-fuchsia-500/30 border-t-fuchsia-500 rounded-full animate-spin" />
                        </div>
                    ) : (
                        <>
                            <ScrollArea 
                                className="h-[400px] p-6"
                                onScroll={handleScroll}
                            >
                                <div className="space-y-6">
                                    {/* Important Warning */}
                                    <div className="p-4 rounded-lg bg-amber-500/10 border border-amber-500/30">
                                        <div className="flex items-start gap-3">
                                            <AlertTriangle className="w-5 h-5 text-amber-400 mt-0.5 flex-shrink-0" />
                                            <div>
                                                <p className="font-semibold text-amber-300">Important Notice</p>
                                                <p className="text-sm text-gray-300 mt-1">
                                                    LittleHelper AI generates code using artificial intelligence. 
                                                    You are responsible for reviewing and testing all generated code 
                                                    before use. We are not liable for any issues arising from the 
                                                    use of AI-generated content.
                                                </p>
                                            </div>
                                        </div>
                                    </div>

                                    {/* Terms Sections */}
                                    {terms?.content?.sections?.map((section, idx) => (
                                        <div key={idx} className="space-y-2">
                                            <h3 className="font-semibold text-white">{section.title}</h3>
                                            <p className="text-sm text-gray-300 leading-relaxed">{section.content}</p>
                                        </div>
                                    ))}

                                    {/* Disclaimer */}
                                    {terms?.content?.disclaimer && (
                                        <div className="p-4 rounded-lg bg-red-500/10 border border-red-500/30 mt-6">
                                            <div className="flex items-start gap-3">
                                                <Shield className="w-5 h-5 text-red-400 mt-0.5 flex-shrink-0" />
                                                <p className="text-sm text-red-300 font-medium">
                                                    {terms.content.disclaimer}
                                                </p>
                                            </div>
                                        </div>
                                    )}

                                    {/* Version */}
                                    <p className="text-xs text-gray-500 pt-4">
                                        Version {terms?.version || '1.0'} • Last updated: January 2025
                                    </p>
                                </div>
                            </ScrollArea>

                            {/* Footer */}
                            <div className="p-6 border-t border-white/10 bg-[#080B12]">
                                <div className="flex flex-col sm:flex-row gap-3">
                                    <Button
                                        variant="outline"
                                        onClick={onDecline}
                                        className="flex-1 border-white/20 hover:bg-white/5"
                                    >
                                        <X size={18} className="mr-2" />
                                        Decline
                                    </Button>
                                    <Button
                                        onClick={onAccept}
                                        className="flex-1 bg-gradient-to-r from-fuchsia-500 to-fuchsia-600 hover:from-fuchsia-600 hover:to-fuchsia-700"
                                    >
                                        <Check size={18} className="mr-2" />
                                        I Accept the Terms
                                    </Button>
                                </div>
                                <p className="text-xs text-gray-500 text-center mt-3">
                                    By clicking "I Accept", you agree to our Terms of Service and Privacy Policy
                                </p>
                            </div>
                        </>
                    )}
                </motion.div>
            </motion.div>
        </AnimatePresence>
    );
}

export default function Register() {
    const [name, setName] = useState('');
    const [email, setEmail] = useState('');
    const [password, setPassword] = useState('');
    const [showPassword, setShowPassword] = useState(false);
    const [tosAccepted, setTosAccepted] = useState(false);
    const [showTOSModal, setShowTOSModal] = useState(false);
    const [error, setError] = useState('');
    const [loading, setLoading] = useState(false);
    const { register } = useAuth();
    const navigate = useNavigate();

    const handleSubmit = async (e) => {
        e.preventDefault();
        setError('');
        
        if (password.length < 6) {
            setError('Password must be at least 6 characters');
            return;
        }

        if (!tosAccepted) {
            setShowTOSModal(true);
            return;
        }
        
        setLoading(true);
        
        try {
            await register(name, email, password, tosAccepted);
            navigate('/dashboard');
        } catch (err) {
            setError(err.response?.data?.detail || 'Registration failed. Please try again.');
        } finally {
            setLoading(false);
        }
    };

    const handleTOSAccept = () => {
        setTosAccepted(true);
        setShowTOSModal(false);
    };

    const handleTOSDecline = () => {
        setTosAccepted(false);
        setShowTOSModal(false);
    };

    const features = [
        '100 free credits to start',
        '7 AI agents at your service',
        'Full code execution',
        'Multi-language support'
    ];

    return (
        <div className="min-h-screen bg-[#030712] grid-bg flex items-center justify-center p-4">
            {/* Background effects */}
            <div className="absolute inset-0 overflow-hidden">
                <div className="absolute top-1/4 right-1/4 w-96 h-96 bg-fuchsia-500/10 rounded-full blur-3xl" />
                <div className="absolute bottom-1/4 left-1/4 w-96 h-96 bg-cyan-500/10 rounded-full blur-3xl" />
            </div>
            
            <motion.div
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.5 }}
                className="relative z-10 w-full max-w-md"
            >
                {/* Back button */}
                <Link 
                    to="/" 
                    className="flex items-center gap-2 text-gray-400 hover:text-white mb-8 transition-colors"
                    data-testid="back-to-home"
                >
                    <ArrowLeft size={20} />
                    <span>Back to home</span>
                </Link>
                
                {/* Card */}
                <div className="glass-card rounded-2xl p-8">
                    {/* Logo */}
                    <div className="flex items-center justify-center gap-3 mb-8">
                        <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-fuchsia-500 to-cyan-500 flex items-center justify-center">
                            <Zap className="w-6 h-6 text-white" />
                        </div>
                        <span className="text-2xl font-bold text-white font-outfit">LittleHelper AI</span>
                    </div>
                    
                    <h1 className="text-2xl font-bold text-center mb-2">Create your account</h1>
                    <p className="text-gray-400 text-center mb-6">Start building with AI today</p>
                    
                    {/* Features */}
                    <div className="grid grid-cols-2 gap-2 mb-6">
                        {features.map((feature, i) => (
                            <div key={i} className="flex items-center gap-2 text-sm text-gray-400">
                                <Check size={14} className="text-green-400" />
                                <span>{feature}</span>
                            </div>
                        ))}
                    </div>
                    
                    {error && (
                        <motion.div
                            initial={{ opacity: 0, y: -10 }}
                            animate={{ opacity: 1, y: 0 }}
                            className="bg-red-500/10 border border-red-500/20 text-red-400 px-4 py-3 rounded-lg mb-6"
                            data-testid="register-error"
                        >
                            {error}
                        </motion.div>
                    )}
                    
                    <form onSubmit={handleSubmit} className="space-y-5">
                        <div className="space-y-2">
                            <Label htmlFor="name">Full Name</Label>
                            <Input
                                id="name"
                                type="text"
                                value={name}
                                onChange={(e) => setName(e.target.value)}
                                placeholder="John Doe"
                                className="bg-white/5 border-white/10 focus:border-fuchsia-500 h-12"
                                required
                                data-testid="name-input"
                            />
                        </div>
                        
                        <div className="space-y-2">
                            <Label htmlFor="email">Email</Label>
                            <Input
                                id="email"
                                type="email"
                                value={email}
                                onChange={(e) => setEmail(e.target.value)}
                                placeholder="you@example.com"
                                className="bg-white/5 border-white/10 focus:border-fuchsia-500 h-12"
                                required
                                data-testid="email-input"
                            />
                        </div>
                        
                        <div className="space-y-2">
                            <Label htmlFor="password">Password</Label>
                            <div className="relative">
                                <Input
                                    id="password"
                                    type={showPassword ? 'text' : 'password'}
                                    value={password}
                                    onChange={(e) => setPassword(e.target.value)}
                                    placeholder="••••••••"
                                    className="bg-white/5 border-white/10 focus:border-fuchsia-500 h-12 pr-12"
                                    required
                                    minLength={6}
                                    data-testid="password-input"
                                />
                                <button
                                    type="button"
                                    onClick={() => setShowPassword(!showPassword)}
                                    className="absolute right-3 top-1/2 -translate-y-1/2 text-gray-400 hover:text-white transition-colors"
                                >
                                    {showPassword ? <EyeOff size={20} /> : <Eye size={20} />}
                                </button>
                            </div>
                            <p className="text-xs text-gray-500">At least 6 characters</p>
                        </div>

                        {/* Terms of Service Checkbox */}
                        <div className="flex items-start gap-3 p-3 rounded-lg bg-white/5 border border-white/10">
                            <Checkbox
                                id="tos"
                                checked={tosAccepted}
                                onCheckedChange={setTosAccepted}
                                className="mt-0.5"
                            />
                            <div className="flex-1">
                                <label htmlFor="tos" className="text-sm text-gray-300 cursor-pointer">
                                    I agree to the{' '}
                                    <button
                                        type="button"
                                        onClick={() => setShowTOSModal(true)}
                                        className="text-fuchsia-400 hover:text-fuchsia-300 underline"
                                    >
                                        Terms of Service
                                    </button>
                                    {' '}and acknowledge that AI-generated code may contain errors
                                </label>
                            </div>
                        </div>
                        
                        <Button
                            type="submit"
                            disabled={loading}
                            className="w-full h-12 bg-gradient-to-r from-fuchsia-500 to-fuchsia-600 hover:from-fuchsia-600 hover:to-fuchsia-700 glow-primary btn-glow"
                            data-testid="register-submit"
                        >
                            {loading ? (
                                <div className="w-5 h-5 border-2 border-white/30 border-t-white rounded-full animate-spin" />
                            ) : (
                                'Create Account'
                            )}
                        </Button>
                    </form>
                    
                    <p className="text-center text-gray-400 mt-6">
                        Already have an account?{' '}
                        <Link 
                            to="/login" 
                            className="text-fuchsia-400 hover:text-fuchsia-300 transition-colors"
                            data-testid="login-link"
                        >
                            Sign in
                        </Link>
                    </p>
                </div>
            </motion.div>

            {/* TOS Modal */}
            <TOSModal
                isOpen={showTOSModal}
                onAccept={handleTOSAccept}
                onDecline={handleTOSDecline}
            />
        </div>
    );
}
