import { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { motion, AnimatePresence } from 'framer-motion';
import { useAuth } from '../../lib/auth';
import { Button } from '../../components/ui/button';
import { Input } from '../../components/ui/input';
import { Label } from '../../components/ui/label';
import { ScrollArea } from '../../components/ui/scroll-area';
import { 
    Eye, EyeOff, Zap, ArrowLeft, Check, X, 
    AlertTriangle, FileText, Shield 
} from 'lucide-react';
import api from '../../lib/api';

// Terms of Service Modal for existing users
function TOSModal({ isOpen, onAccept, onDecline }) {
    const [terms, setTerms] = useState(null);
    const [loading, setLoading] = useState(true);
    const [accepting, setAccepting] = useState(false);

    useState(() => {
        if (isOpen) {
            loadTerms();
        }
    }, [isOpen]);

    const loadTerms = async () => {
        try {
            const res = await api.get('/legal/terms');
            setTerms(res.data);
        } catch (error) {
            setTerms({
                version: "1.0",
                content: {
                    title: "Terms of Service",
                    sections: [
                        {
                            title: "1. Acceptance of Terms",
                            content: "By accessing or using LittleHelper AI, you agree to be bound by these Terms of Service."
                        },
                        {
                            title: "2. No Warranty",
                            content: "THE SERVICE IS PROVIDED 'AS IS' AND 'AS AVAILABLE' WITHOUT WARRANTIES OF ANY KIND."
                        },
                        {
                            title: "3. Limitation of Liability",
                            content: "WE SHALL NOT BE LIABLE FOR ANY DAMAGES RESULTING FROM YOUR USE OF THE SERVICE OR ANY CODE GENERATED."
                        },
                        {
                            title: "4. User Responsibility",
                            content: "You are solely responsible for reviewing, testing, and validating all code generated by the Service."
                        }
                    ],
                    disclaimer: "BY USING THIS SERVICE, YOU ACKNOWLEDGE THAT AI-GENERATED CODE MAY CONTAIN ERRORS AND YOU ASSUME ALL RISKS."
                }
            });
        } finally {
            setLoading(false);
        }
    };

    const handleAccept = async () => {
        setAccepting(true);
        try {
            await api.post('/auth/accept-tos');
            onAccept();
        } catch (error) {
            console.error('Failed to accept TOS:', error);
        } finally {
            setAccepting(false);
        }
    };

    if (!isOpen) return null;

    return (
        <AnimatePresence>
            <motion.div
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                exit={{ opacity: 0 }}
                className="fixed inset-0 z-50 flex items-center justify-center bg-black/80 backdrop-blur-sm p-4"
            >
                <motion.div
                    initial={{ opacity: 0, scale: 0.95, y: 20 }}
                    animate={{ opacity: 1, scale: 1, y: 0 }}
                    exit={{ opacity: 0, scale: 0.95, y: 20 }}
                    className="w-full max-w-2xl bg-[#0B0F19] border border-white/10 rounded-2xl shadow-2xl overflow-hidden"
                >
                    {/* Header */}
                    <div className="p-6 border-b border-white/10 bg-gradient-to-r from-fuchsia-500/10 to-cyan-500/10">
                        <div className="flex items-center gap-3">
                            <div className="w-12 h-12 rounded-xl bg-gradient-to-br from-fuchsia-500 to-cyan-500 flex items-center justify-center">
                                <FileText className="w-6 h-6 text-white" />
                            </div>
                            <div>
                                <h2 className="text-xl font-bold">Updated Terms of Service</h2>
                                <p className="text-sm text-gray-400">Please review and accept to continue</p>
                            </div>
                        </div>
                    </div>

                    {/* Content */}
                    {loading ? (
                        <div className="p-8 flex items-center justify-center">
                            <div className="w-8 h-8 border-2 border-fuchsia-500/30 border-t-fuchsia-500 rounded-full animate-spin" />
                        </div>
                    ) : (
                        <>
                            <ScrollArea className="h-[400px] p-6">
                                <div className="space-y-6">
                                    {/* Important Warning */}
                                    <div className="p-4 rounded-lg bg-amber-500/10 border border-amber-500/30">
                                        <div className="flex items-start gap-3">
                                            <AlertTriangle className="w-5 h-5 text-amber-400 mt-0.5 flex-shrink-0" />
                                            <div>
                                                <p className="font-semibold text-amber-300">Important Notice</p>
                                                <p className="text-sm text-gray-300 mt-1">
                                                    We&apos;ve updated our Terms of Service. Please review and accept 
                                                    the new terms to continue using LittleHelper AI.
                                                </p>
                                            </div>
                                        </div>
                                    </div>

                                    {/* Terms Sections */}
                                    {terms?.content?.sections?.map((section, idx) => (
                                        <div key={idx} className="space-y-2">
                                            <h3 className="font-semibold text-white">{section.title}</h3>
                                            <p className="text-sm text-gray-300 leading-relaxed">{section.content}</p>
                                        </div>
                                    ))}

                                    {/* Disclaimer */}
                                    {terms?.content?.disclaimer && (
                                        <div className="p-4 rounded-lg bg-red-500/10 border border-red-500/30 mt-6">
                                            <div className="flex items-start gap-3">
                                                <Shield className="w-5 h-5 text-red-400 mt-0.5 flex-shrink-0" />
                                                <p className="text-sm text-red-300 font-medium">
                                                    {terms.content.disclaimer}
                                                </p>
                                            </div>
                                        </div>
                                    )}

                                    <p className="text-xs text-gray-500 pt-4">
                                        Version {terms?.version || '1.0'} • Last updated: January 2025
                                    </p>
                                </div>
                            </ScrollArea>

                            {/* Footer */}
                            <div className="p-6 border-t border-white/10 bg-[#080B12]">
                                <div className="flex flex-col sm:flex-row gap-3">
                                    <Button
                                        variant="outline"
                                        onClick={onDecline}
                                        className="flex-1 border-white/20 hover:bg-white/5"
                                    >
                                        <X size={18} className="mr-2" />
                                        Decline & Log Out
                                    </Button>
                                    <Button
                                        onClick={handleAccept}
                                        disabled={accepting}
                                        className="flex-1 bg-gradient-to-r from-fuchsia-500 to-fuchsia-600 hover:from-fuchsia-600 hover:to-fuchsia-700"
                                    >
                                        {accepting ? (
                                            <div className="w-5 h-5 border-2 border-white/30 border-t-white rounded-full animate-spin" />
                                        ) : (
                                            <>
                                                <Check size={18} className="mr-2" />
                                                I Accept the Terms
                                            </>
                                        )}
                                    </Button>
                                </div>
                                <p className="text-xs text-gray-500 text-center mt-3">
                                    You must accept the Terms of Service to continue using LittleHelper AI
                                </p>
                            </div>
                        </>
                    )}
                </motion.div>
            </motion.div>
        </AnimatePresence>
    );
}

export default function Login() {
    const [email, setEmail] = useState('');
    const [password, setPassword] = useState('');
    const [showPassword, setShowPassword] = useState(false);
    const [error, setError] = useState('');
    const [loading, setLoading] = useState(false);
    const [showTOSModal, setShowTOSModal] = useState(false);
    const [pendingUser, setPendingUser] = useState(null);
    const { login, logout } = useAuth();
    const navigate = useNavigate();

    const handleSubmit = async (e) => {
        e.preventDefault();
        setError('');
        setLoading(true);
        
        try {
            const userData = await login(email, password);
            
            // Check if user needs to accept TOS
            if (userData && userData.tos_accepted === false) {
                setPendingUser(userData);
                setShowTOSModal(true);
            } else {
                navigate('/dashboard');
            }
        } catch (err) {
            setError(err.response?.data?.detail || 'Login failed. Please try again.');
        } finally {
            setLoading(false);
        }
    };

    const handleTOSAccept = () => {
        setShowTOSModal(false);
        navigate('/dashboard');
    };

    const handleTOSDecline = () => {
        setShowTOSModal(false);
        logout();
        setError('You must accept the Terms of Service to use LittleHelper AI');
    };

    return (
        <div className="min-h-screen bg-[#030712] grid-bg flex items-center justify-center p-4">
            {/* Background effects */}
            <div className="absolute inset-0 overflow-hidden">
                <div className="absolute top-1/4 left-1/4 w-96 h-96 bg-fuchsia-500/10 rounded-full blur-3xl" />
                <div className="absolute bottom-1/4 right-1/4 w-96 h-96 bg-cyan-500/10 rounded-full blur-3xl" />
            </div>
            
            <motion.div
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.5 }}
                className="relative z-10 w-full max-w-md"
            >
                {/* Back button */}
                <Link 
                    to="/" 
                    className="flex items-center gap-2 text-gray-400 hover:text-white mb-8 transition-colors"
                    data-testid="back-to-home"
                >
                    <ArrowLeft size={20} />
                    <span>Back to home</span>
                </Link>
                
                {/* Card */}
                <div className="glass-card rounded-2xl p-8">
                    {/* Logo */}
                    <div className="flex items-center justify-center gap-3 mb-8">
                        <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-fuchsia-500 to-cyan-500 flex items-center justify-center">
                            <Zap className="w-6 h-6 text-white" />
                        </div>
                        <span className="text-2xl font-bold text-white font-outfit">LittleHelper AI</span>
                    </div>
                    
                    <h1 className="text-2xl font-bold text-center mb-2">Welcome back</h1>
                    <p className="text-gray-400 text-center mb-8">Sign in to continue building</p>
                    
                    {error && (
                        <motion.div
                            initial={{ opacity: 0, y: -10 }}
                            animate={{ opacity: 1, y: 0 }}
                            className={`px-4 py-3 rounded-lg mb-6 ${
                                error.includes('Backend unavailable') || error.includes('connection')
                                    ? 'bg-amber-500/10 border border-amber-500/20'
                                    : 'bg-red-500/10 border border-red-500/20'
                            }`}
                            data-testid="login-error"
                        >
                            {error.includes('Backend unavailable') || error.includes('connection') ? (
                                <div className="space-y-2">
                                    <div className="flex items-center gap-2 text-amber-400">
                                        <AlertTriangle size={18} />
                                        <span className="font-medium">Service Temporarily Unavailable</span>
                                    </div>
                                    <p className="text-sm text-amber-300/80">
                                        The server is currently starting up or undergoing maintenance. Please try again in a moment.
                                    </p>
                                    <Button
                                        type="button"
                                        variant="outline"
                                        size="sm"
                                        onClick={() => { setError(''); setLoading(false); }}
                                        className="mt-2 border-amber-500/30 text-amber-400 hover:bg-amber-500/10"
                                    >
                                        Dismiss
                                    </Button>
                                </div>
                            ) : (
                                <span className="text-red-400">{error}</span>
                            )}
                        </motion.div>
                    )}
                    
                    <form onSubmit={handleSubmit} className="space-y-6">
                        <div className="space-y-2">
                            <Label htmlFor="email">Email</Label>
                            <Input
                                id="email"
                                type="email"
                                value={email}
                                onChange={(e) => setEmail(e.target.value)}
                                placeholder="you@example.com"
                                className="bg-white/5 border-white/10 focus:border-fuchsia-500 h-12"
                                required
                                data-testid="email-input"
                            />
                        </div>
                        
                        <div className="space-y-2">
                            <Label htmlFor="password">Password</Label>
                            <div className="relative">
                                <Input
                                    id="password"
                                    type={showPassword ? 'text' : 'password'}
                                    value={password}
                                    onChange={(e) => setPassword(e.target.value)}
                                    placeholder="••••••••"
                                    className="bg-white/5 border-white/10 focus:border-fuchsia-500 h-12 pr-12"
                                    required
                                    data-testid="password-input"
                                />
                                <button
                                    type="button"
                                    onClick={() => setShowPassword(!showPassword)}
                                    className="absolute right-3 top-1/2 -translate-y-1/2 text-gray-400 hover:text-white transition-colors"
                                >
                                    {showPassword ? <EyeOff size={20} /> : <Eye size={20} />}
                                </button>
                            </div>
                        </div>
                        
                        <Button
                            type="submit"
                            disabled={loading}
                            className="w-full h-12 bg-gradient-to-r from-fuchsia-500 to-fuchsia-600 hover:from-fuchsia-600 hover:to-fuchsia-700 glow-primary btn-glow"
                            data-testid="login-submit"
                        >
                            {loading ? (
                                <div className="w-5 h-5 border-2 border-white/30 border-t-white rounded-full animate-spin" />
                            ) : (
                                'Sign In'
                            )}
                        </Button>
                    </form>
                    
                    <p className="text-center text-gray-400 mt-6">
                        Don&apos;t have an account?{' '}
                        <Link 
                            to="/register" 
                            className="text-fuchsia-400 hover:text-fuchsia-300 transition-colors"
                            data-testid="register-link"
                        >
                            Sign up
                        </Link>
                    </p>
                </div>
            </motion.div>

            {/* TOS Modal for existing users */}
            <TOSModal
                isOpen={showTOSModal}
                onAccept={handleTOSAccept}
                onDecline={handleTOSDecline}
            />
        </div>
    );
}
