import { useState, useEffect } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { motion, AnimatePresence } from 'framer-motion';
import { useAuth } from '../../lib/auth';
import { Button } from '../../components/ui/button';
import { Input } from '../../components/ui/input';
import { Label } from '../../components/ui/label';
import { ScrollArea } from '../../components/ui/scroll-area';
import { 
    Eye, EyeOff, Zap, ArrowLeft, Check, X, 
    AlertTriangle, FileText, Shield 
} from 'lucide-react';
import api from '../../lib/api';

// Terms of Service Modal Component
function TOSModal({ isOpen, onAccept, onDecline }) {
    const [terms, setTerms] = useState(null);
    const [loading, setLoading] = useState(true);
    const [scrolledToEnd, setScrolledToEnd] = useState(false);

    useEffect(() => {
        if (isOpen) {
            loadTerms();
        }
    }, [isOpen]);

    const loadTerms = async () => {
        try {
            const res = await api.get('/legal/terms');
            setTerms(res.data);
        } catch (error) {
            // Use default terms if API fails
            setTerms({
                version: "1.0",
                content: {
                    title: "Terms of Service",
                    sections: [
                        {
                            title: "1. Acceptance of Terms",
                            content: "By accessing or using LittleHelper AI, you agree to be bound by these Terms of Service. If you do not agree to all the terms and conditions, you may not access or use the Service."
                        },
                        {
                            title: "2. Description of Service",
                            content: "LittleHelper AI provides AI-powered code generation, debugging, and software development assistance. The Service uses artificial intelligence models to generate code and provide development recommendations."
                        },
                        {
                            title: "3. No Warranty",
                            content: "THE SERVICE IS PROVIDED 'AS IS' AND 'AS AVAILABLE' WITHOUT WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED. WE DO NOT WARRANT THAT THE SERVICE WILL BE UNINTERRUPTED, ERROR-FREE, OR THAT ANY CODE GENERATED WILL BE FREE OF BUGS OR SECURITY VULNERABILITIES."
                        },
                        {
                            title: "4. Limitation of Liability",
                            content: "IN NO EVENT SHALL LITTLEHELPER AI BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING BUT NOT LIMITED TO LOSS OF PROFITS, DATA, USE, OR GOODWILL, ARISING OUT OF OR IN CONNECTION WITH YOUR USE OF THE SERVICE OR ANY CODE GENERATED."
                        },
                        {
                            title: "5. User Responsibility",
                            content: "You are solely responsible for reviewing, testing, and validating all code generated by the Service before deploying it in any production environment. You agree to test all generated code in a safe environment and ensure it meets your security and quality standards."
                        },
                        {
                            title: "6. AI-Generated Content",
                            content: "All code and content generated by the Service is produced by artificial intelligence. While we strive for accuracy, AI-generated code may contain errors, bugs, security vulnerabilities, or may not work as expected. You acknowledge these limitations."
                        },
                        {
                            title: "7. Acceptable Use",
                            content: "You agree not to use the Service for any illegal purposes, to generate malicious code, or to violate any applicable laws. You are responsible for ensuring your use of the Service complies with all applicable laws and regulations."
                        },
                        {
                            title: "8. Account Security",
                            content: "You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account. You agree to notify us immediately of any unauthorized use of your account."
                        },
                        {
                            title: "9. Credits and Payments",
                            content: "Credits are non-refundable unless required by applicable law. Unused credits expire according to your subscription plan terms. All fees are stated in USD and do not include applicable taxes."
                        },
                        {
                            title: "10. Termination",
                            content: "We reserve the right to suspend or terminate your access to the Service at any time, with or without cause. Upon termination, your right to use the Service will immediately cease."
                        }
                    ],
                    disclaimer: "BY USING THIS SERVICE, YOU ACKNOWLEDGE THAT AI-GENERATED CODE MAY CONTAIN ERRORS, SECURITY VULNERABILITIES, OR OTHER ISSUES. YOU ASSUME ALL RISKS ASSOCIATED WITH THE USE OF ANY CODE OR CONTENT GENERATED BY THE SERVICE."
                }
            });
        } finally {
            setLoading(false);
        }
    };

    const handleScroll = (e) => {
        const { scrollTop, scrollHeight, clientHeight } = e.target;
        if (scrollTop + clientHeight >= scrollHeight - 20) {
            setScrolledToEnd(true);
        }
    };

    if (!isOpen) return null;

    return (
        <AnimatePresence>
            <motion.div
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                exit={{ opacity: 0 }}
                className="fixed inset-0 z-50 flex items-center justify-center bg-black/80 backdrop-blur-sm p-4"
                data-testid="tos-modal"
            >
                <motion.div
                    initial={{ opacity: 0, scale: 0.95, y: 20 }}
                    animate={{ opacity: 1, scale: 1, y: 0 }}
                    exit={{ opacity: 0, scale: 0.95, y: 20 }}
                    className="w-full max-w-2xl bg-[#0B0F19] border border-white/10 rounded-2xl shadow-2xl overflow-hidden"
                >
                    {/* Header */}
                    <div className="p-6 border-b border-white/10 bg-gradient-to-r from-fuchsia-500/10 to-cyan-500/10">
                        <div className="flex items-center gap-3">
                            <div className="w-12 h-12 rounded-xl bg-gradient-to-br from-fuchsia-500 to-cyan-500 flex items-center justify-center">
                                <FileText className="w-6 h-6 text-white" />
                            </div>
                            <div>
                                <h2 className="text-xl font-bold">Terms of Service</h2>
                                <p className="text-sm text-gray-400">Please read and accept to continue</p>
                            </div>
                        </div>
                    </div>

                    {/* Content */}
                    {loading ? (
                        <div className="p-8 flex items-center justify-center">
                            <div className="w-8 h-8 border-2 border-fuchsia-500/30 border-t-fuchsia-500 rounded-full animate-spin" />
                        </div>
                    ) : (
                        <>
                            <ScrollArea 
                                className="h-[400px] p-6"
                                onScroll={handleScroll}
                            >
                                <div className="space-y-6">
                                    {/* Important Warning */}
                                    <div className="p-4 rounded-lg bg-amber-500/10 border border-amber-500/30">
                                        <div className="flex items-start gap-3">
                                            <AlertTriangle className="w-5 h-5 text-amber-400 mt-0.5 flex-shrink-0" />
                                            <div>
                                                <p className="font-semibold text-amber-300">Important Notice</p>
                                                <p className="text-sm text-gray-300 mt-1">
                                                    LittleHelper AI generates code using artificial intelligence. 
                                                    You are responsible for reviewing and testing all generated code 
                                                    before use. We are not liable for any issues arising from the 
                                                    use of AI-generated content.
                                                </p>
                                            </div>
                                        </div>
                                    </div>

                                    {/* Terms Sections */}
                                    {terms?.content?.sections?.map((section, idx) => (
                                        <div key={idx} className="space-y-2">
                                            <h3 className="font-semibold text-white">{section.title}</h3>
                                            <p className="text-sm text-gray-300 leading-relaxed">{section.content}</p>
                                        </div>
                                    ))}

                                    {/* Disclaimer */}
                                    {terms?.content?.disclaimer && (
                                        <div className="p-4 rounded-lg bg-red-500/10 border border-red-500/30 mt-6">
                                            <div className="flex items-start gap-3">
                                                <Shield className="w-5 h-5 text-red-400 mt-0.5 flex-shrink-0" />
                                                <p className="text-sm text-red-300 font-medium">
                                                    {terms.content.disclaimer}
                                                </p>
                                            </div>
                                        </div>
                                    )}

                                    {/* Version */}
                                    <p className="text-xs text-gray-500 pt-4">
                                        Version {terms?.version || '1.0'} • Last updated: January 2025
                                    </p>
                                </div>
                            </ScrollArea>

                            {/* Footer with Accept/Decline buttons */}
                            <div className="p-6 border-t border-white/10 bg-[#080B12]">
                                <div className="flex flex-col sm:flex-row gap-3">
                                    <Button
                                        variant="outline"
                                        onClick={onDecline}
                                        className="flex-1 border-white/20 hover:bg-white/5"
                                        data-testid="tos-decline-btn"
                                    >
                                        <X size={18} className="mr-2" />
                                        Decline
                                    </Button>
                                    <Button
                                        onClick={onAccept}
                                        className="flex-1 bg-gradient-to-r from-fuchsia-500 to-fuchsia-600 hover:from-fuchsia-600 hover:to-fuchsia-700"
                                        data-testid="tos-accept-btn"
                                    >
                                        <Check size={18} className="mr-2" />
                                        Accept & Continue
                                    </Button>
                                </div>
                                <p className="text-xs text-gray-500 text-center mt-3">
                                    By clicking "Accept & Continue", you agree to our Terms of Service and Privacy Policy
                                </p>
                            </div>
                        </>
                    )}
                </motion.div>
            </motion.div>
        </AnimatePresence>
    );
}

export default function Register() {
    const [name, setName] = useState('');
    const [email, setEmail] = useState('');
    const [password, setPassword] = useState('');
    const [confirmPassword, setConfirmPassword] = useState('');
    const [showPassword, setShowPassword] = useState(false);
    const [showConfirmPassword, setShowConfirmPassword] = useState(false);
    const [showTOSModal, setShowTOSModal] = useState(false);
    const [pendingRegistration, setPendingRegistration] = useState(false);
    const [error, setError] = useState('');
    const [loading, setLoading] = useState(false);
    const { register } = useAuth();
    const navigate = useNavigate();

    // Password strength indicator
    const getPasswordStrength = (pwd) => {
        if (!pwd) return { level: 0, text: '', color: '' };
        let score = 0;
        if (pwd.length >= 6) score++;
        if (pwd.length >= 8) score++;
        if (/[A-Z]/.test(pwd)) score++;
        if (/[0-9]/.test(pwd)) score++;
        if (/[^A-Za-z0-9]/.test(pwd)) score++;

        if (score <= 2) return { level: score, text: 'Weak', color: 'bg-red-500' };
        if (score <= 3) return { level: score, text: 'Fair', color: 'bg-yellow-500' };
        if (score <= 4) return { level: score, text: 'Good', color: 'bg-green-500' };
        return { level: score, text: 'Strong', color: 'bg-emerald-500' };
    };

    const passwordStrength = getPasswordStrength(password);

    const handleSubmit = async (e) => {
        e.preventDefault();
        setError('');
        
        // Validation
        if (password.length < 6) {
            setError('Password must be at least 6 characters');
            return;
        }

        if (password !== confirmPassword) {
            setError('Passwords do not match');
            return;
        }

        // Show TOS modal - registration will proceed after accepting
        setPendingRegistration(true);
        setShowTOSModal(true);
    };

    const handleTOSAccept = async () => {
        setShowTOSModal(false);
        
        if (pendingRegistration) {
            setLoading(true);
            try {
                await register(name, email, password, true); // true = TOS accepted
                navigate('/dashboard');
            } catch (err) {
                setError(err.response?.data?.detail || 'Registration failed. Please try again.');
            } finally {
                setLoading(false);
                setPendingRegistration(false);
            }
        }
    };

    const handleTOSDecline = () => {
        setShowTOSModal(false);
        setPendingRegistration(false);
        setError('You must accept the Terms of Service to create an account.');
    };

    const features = [
        '100 free credits to start',
        '7 AI agents at your service',
        'Full code execution',
        'Multi-language support'
    ];

    return (
        <div className="min-h-screen bg-[#030712] grid-bg flex items-center justify-center p-4">
            {/* Background effects */}
            <div className="absolute inset-0 overflow-hidden">
                <div className="absolute top-1/4 right-1/4 w-96 h-96 bg-fuchsia-500/10 rounded-full blur-3xl" />
                <div className="absolute bottom-1/4 left-1/4 w-96 h-96 bg-cyan-500/10 rounded-full blur-3xl" />
            </div>
            
            <motion.div
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.5 }}
                className="relative z-10 w-full max-w-md"
            >
                {/* Back button */}
                <Link 
                    to="/" 
                    className="flex items-center gap-2 text-gray-400 hover:text-white mb-8 transition-colors"
                    data-testid="back-to-home"
                >
                    <ArrowLeft size={20} />
                    <span>Back to home</span>
                </Link>
                
                {/* Card */}
                <div className="glass-card rounded-2xl p-8">
                    {/* Logo */}
                    <div className="flex items-center justify-center gap-3 mb-8">
                        <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-fuchsia-500 to-cyan-500 flex items-center justify-center">
                            <Zap className="w-6 h-6 text-white" />
                        </div>
                        <span className="text-2xl font-bold text-white font-outfit">LittleHelper AI</span>
                    </div>
                    
                    <h1 className="text-2xl font-bold text-center mb-2">Create your account</h1>
                    <p className="text-gray-400 text-center mb-6">Start building with AI today</p>
                    
                    {/* Features */}
                    <div className="grid grid-cols-2 gap-2 mb-6">
                        {features.map((feature, i) => (
                            <div key={i} className="flex items-center gap-2 text-sm text-gray-400">
                                <Check size={14} className="text-green-400" />
                                <span>{feature}</span>
                            </div>
                        ))}
                    </div>
                    
                    {error && (
                        <motion.div
                            initial={{ opacity: 0, y: -10 }}
                            animate={{ opacity: 1, y: 0 }}
                            className={`px-4 py-3 rounded-lg mb-6 ${
                                error.includes('Backend unavailable') || error.includes('connection')
                                    ? 'bg-amber-500/10 border border-amber-500/20'
                                    : 'bg-red-500/10 border border-red-500/20'
                            }`}
                            data-testid="register-error"
                        >
                            {error.includes('Backend unavailable') || error.includes('connection') ? (
                                <div className="space-y-2">
                                    <div className="flex items-center gap-2 text-amber-400">
                                        <AlertTriangle size={18} />
                                        <span className="font-medium">Service Temporarily Unavailable</span>
                                    </div>
                                    <p className="text-sm text-amber-300/80">
                                        The server is currently starting up or undergoing maintenance. Please try again in a moment.
                                    </p>
                                    <Button
                                        type="button"
                                        variant="outline"
                                        size="sm"
                                        onClick={() => { setError(''); setLoading(false); }}
                                        className="mt-2 border-amber-500/30 text-amber-400 hover:bg-amber-500/10"
                                    >
                                        Dismiss
                                    </Button>
                                </div>
                            ) : (
                                <span className="text-red-400">{error}</span>
                            )}
                        </motion.div>
                    )}
                    
                    <form onSubmit={handleSubmit} className="space-y-5">
                        <div className="space-y-2">
                            <Label htmlFor="name">Full Name</Label>
                            <Input
                                id="name"
                                type="text"
                                value={name}
                                onChange={(e) => setName(e.target.value)}
                                placeholder="John Doe"
                                className="bg-white/5 border-white/10 focus:border-fuchsia-500 h-12"
                                required
                                data-testid="name-input"
                            />
                        </div>
                        
                        <div className="space-y-2">
                            <Label htmlFor="email">Email</Label>
                            <Input
                                id="email"
                                type="email"
                                value={email}
                                onChange={(e) => setEmail(e.target.value)}
                                placeholder="you@example.com"
                                className="bg-white/5 border-white/10 focus:border-fuchsia-500 h-12"
                                required
                                data-testid="email-input"
                            />
                        </div>
                        
                        <div className="space-y-2">
                            <Label htmlFor="password">Password</Label>
                            <div className="relative">
                                <Input
                                    id="password"
                                    type={showPassword ? 'text' : 'password'}
                                    value={password}
                                    onChange={(e) => setPassword(e.target.value)}
                                    placeholder="••••••••"
                                    className="bg-white/5 border-white/10 focus:border-fuchsia-500 h-12 pr-12"
                                    required
                                    minLength={6}
                                    data-testid="password-input"
                                />
                                <button
                                    type="button"
                                    onClick={() => setShowPassword(!showPassword)}
                                    className="absolute right-3 top-1/2 -translate-y-1/2 text-gray-400 hover:text-white transition-colors"
                                >
                                    {showPassword ? <EyeOff size={20} /> : <Eye size={20} />}
                                </button>
                            </div>
                            {/* Password strength indicator */}
                            {password && (
                                <div className="space-y-1">
                                    <div className="flex gap-1">
                                        {[1, 2, 3, 4, 5].map((level) => (
                                            <div
                                                key={level}
                                                className={`h-1 flex-1 rounded ${
                                                    level <= passwordStrength.level 
                                                        ? passwordStrength.color 
                                                        : 'bg-white/10'
                                                }`}
                                            />
                                        ))}
                                    </div>
                                    <p className="text-xs text-gray-500">
                                        Password strength: <span className={passwordStrength.level >= 3 ? 'text-green-400' : 'text-yellow-400'}>{passwordStrength.text}</span>
                                    </p>
                                </div>
                            )}
                            <p className="text-xs text-gray-500">At least 6 characters</p>
                        </div>

                        {/* Confirm Password Field */}
                        <div className="space-y-2">
                            <Label htmlFor="confirmPassword">Confirm Password</Label>
                            <div className="relative">
                                <Input
                                    id="confirmPassword"
                                    type={showConfirmPassword ? 'text' : 'password'}
                                    value={confirmPassword}
                                    onChange={(e) => setConfirmPassword(e.target.value)}
                                    placeholder="••••••••"
                                    className={`bg-white/5 border-white/10 focus:border-fuchsia-500 h-12 pr-12 ${
                                        confirmPassword && password !== confirmPassword ? 'border-red-500/50' : ''
                                    }`}
                                    required
                                    data-testid="confirm-password-input"
                                />
                                <button
                                    type="button"
                                    onClick={() => setShowConfirmPassword(!showConfirmPassword)}
                                    className="absolute right-3 top-1/2 -translate-y-1/2 text-gray-400 hover:text-white transition-colors"
                                >
                                    {showConfirmPassword ? <EyeOff size={20} /> : <Eye size={20} />}
                                </button>
                            </div>
                            {confirmPassword && password !== confirmPassword && (
                                <p className="text-xs text-red-400">Passwords do not match</p>
                            )}
                            {confirmPassword && password === confirmPassword && confirmPassword.length >= 6 && (
                                <p className="text-xs text-green-400 flex items-center gap-1">
                                    <Check size={12} /> Passwords match
                                </p>
                            )}
                        </div>
                        
                        <Button
                            type="submit"
                            disabled={loading || (confirmPassword && password !== confirmPassword)}
                            className="w-full h-12 bg-gradient-to-r from-fuchsia-500 to-fuchsia-600 hover:from-fuchsia-600 hover:to-fuchsia-700 glow-primary btn-glow"
                            data-testid="register-submit"
                        >
                            {loading ? (
                                <div className="w-5 h-5 border-2 border-white/30 border-t-white rounded-full animate-spin" />
                            ) : (
                                'Create Account'
                            )}
                        </Button>

                        <p className="text-xs text-gray-500 text-center">
                            By clicking "Create Account", you will be asked to review and accept our Terms of Service
                        </p>
                    </form>
                    
                    <p className="text-center text-gray-400 mt-6">
                        Already have an account?{' '}
                        <Link 
                            to="/login" 
                            className="text-fuchsia-400 hover:text-fuchsia-300 transition-colors"
                            data-testid="login-link"
                        >
                            Sign in
                        </Link>
                    </p>
                </div>
            </motion.div>

            {/* TOS Modal - shown after clicking Create Account */}
            <TOSModal
                isOpen={showTOSModal}
                onAccept={handleTOSAccept}
                onDecline={handleTOSDecline}
            />
        </div>
    );
}
