// Legal Controller - Terms of Service
using Microsoft.AspNetCore.Mvc;

namespace LittleHelperAI.API.Controllers;

[ApiController]
[Route("api/legal")]
public class LegalController : ControllerBase
{
    [HttpGet("terms")]
    public ActionResult GetTermsOfService()
    {
        return Ok(new
        {
            version = "1.0",
            last_updated = "2025-01-07",
            content = new
            {
                title = "Terms of Service",
                sections = new[]
                {
                    new
                    {
                        title = "1. Acceptance of Terms",
                        content = "By accessing or using LittleHelper AI ('the Service'), you agree to be bound by these Terms of Service. If you do not agree to these terms, do not use the Service."
                    },
                    new
                    {
                        title = "2. Service Description",
                        content = "LittleHelper AI is an AI-powered code generation and development platform. The Service uses artificial intelligence to generate code, documentation, and other software-related content based on user inputs."
                    },
                    new
                    {
                        title = "3. No Warranty",
                        content = "THE SERVICE IS PROVIDED 'AS IS' AND 'AS AVAILABLE' WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED. WE DO NOT WARRANT THAT THE SERVICE WILL BE UNINTERRUPTED, SECURE, OR ERROR-FREE, OR THAT ANY CODE GENERATED WILL BE ACCURATE, COMPLETE, OR FIT FOR ANY PARTICULAR PURPOSE."
                    },
                    new
                    {
                        title = "4. Limitation of Liability",
                        content = "TO THE MAXIMUM EXTENT PERMITTED BY LAW, LITTLEHELPER AI AND ITS OPERATORS SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING BUT NOT LIMITED TO LOSS OF PROFITS, DATA, USE, OR OTHER INTANGIBLE LOSSES, RESULTING FROM YOUR USE OF THE SERVICE OR ANY CODE GENERATED BY THE SERVICE."
                    },
                    new
                    {
                        title = "5. User Responsibility",
                        content = "You are solely responsible for: (a) reviewing, testing, and validating all code generated by the Service before use; (b) ensuring any generated code complies with applicable laws and regulations; (c) any consequences arising from the use of generated code in production environments; (d) maintaining appropriate backups of your work."
                    },
                    new
                    {
                        title = "6. Intellectual Property",
                        content = "Code generated by the Service may be used by you subject to these terms. You acknowledge that AI-generated content may not be eligible for copyright protection in all jurisdictions. We make no claims regarding the originality or uniqueness of generated content."
                    },
                    new
                    {
                        title = "7. Prohibited Uses",
                        content = "You may not use the Service to: (a) generate malicious code, malware, or exploits; (b) violate any applicable laws or regulations; (c) infringe on intellectual property rights; (d) generate content that is illegal, harmful, or offensive; (e) attempt to bypass security measures or abuse the Service."
                    },
                    new
                    {
                        title = "8. Indemnification",
                        content = "You agree to indemnify, defend, and hold harmless LittleHelper AI and its operators from any claims, damages, losses, or expenses arising from your use of the Service, your violation of these terms, or your violation of any rights of another party."
                    },
                    new
                    {
                        title = "9. Modifications",
                        content = "We reserve the right to modify these Terms of Service at any time. Continued use of the Service after modifications constitutes acceptance of the updated terms."
                    },
                    new
                    {
                        title = "10. Governing Law",
                        content = "These Terms shall be governed by and construed in accordance with applicable laws, without regard to conflict of law principles."
                    }
                },
                disclaimer = "BY USING THIS SERVICE, YOU ACKNOWLEDGE THAT YOU HAVE READ, UNDERSTOOD, AND AGREE TO BE BOUND BY THESE TERMS OF SERVICE. YOU UNDERSTAND THAT AI-GENERATED CODE MAY CONTAIN ERRORS, BUGS, OR SECURITY VULNERABILITIES, AND YOU ASSUME ALL RISKS ASSOCIATED WITH ITS USE."
            }
        });
    }

    [HttpGet("privacy")]
    public ActionResult GetPrivacyPolicy()
    {
        return Ok(new
        {
            version = "1.0",
            last_updated = "2025-01-07",
            content = new
            {
                title = "Privacy Policy",
                sections = new[]
                {
                    new
                    {
                        title = "1. Information We Collect",
                        content = "We collect information you provide directly, including: email address, name, usage data, and any code or content you submit for AI processing."
                    },
                    new
                    {
                        title = "2. How We Use Information",
                        content = "We use your information to provide and improve our services, process payments, communicate with you, and ensure platform security."
                    },
                    new
                    {
                        title = "3. Data Retention",
                        content = "We retain your data for as long as your account is active. You may request deletion of your data at any time."
                    },
                    new
                    {
                        title = "4. Security",
                        content = "We implement industry-standard security measures to protect your data. However, no system is completely secure."
                    }
                }
            }
        });
    }
}
